---
- name: Install Redis
  apt:
    name:
      - redis-server
      - python3-redis
    state: present

- name: Check Redis config file locations
  stat:
    path: "{{ item }}"
  register: redis_config_files
  loop:
    - /etc/redis/redis.conf
    - /etc/redis.conf
    - /etc/redis/6379.conf

- name: Set Redis config path
  set_fact:
    redis_config_path: "{{ item.item }}"
  when: item.stat.exists
  loop: "{{ redis_config_files.results }}"
  loop_control:
    label: "{{ item.item }}"

- name: Configure Redis
  lineinfile:
    path: "{{ redis_config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  loop:
    - { regexp: '^bind', line: 'bind 127.0.0.1' }
    - { regexp: '^# maxmemory <bytes>', line: 'maxmemory 256mb' }
    - { regexp: '^# maxmemory-policy', line: 'maxmemory-policy allkeys-lru' }
    - { regexp: '^save', line: 'save 900 1' }
    - { regexp: '^appendonly', line: 'appendonly yes' }
  when: redis_config_path is defined
  notify: restart redis

- name: Set Redis password if defined
  lineinfile:
    path: "{{ redis_config_path }}"
    regexp: '^# requirepass'
    line: 'requirepass {{ redis_password }}'
    backup: yes
  when: redis_password != "" and redis_config_path is defined
  notify: restart redis

- name: Debug Redis config issue
  debug:
    msg: "Redis config file not found. Checked: /etc/redis/redis.conf, /etc/redis.conf, /etc/redis/6379.conf"
  when: redis_config_path is not defined

- name: Start and enable Redis
  systemd:
    name: redis-server
    state: started
    enabled: yes

- name: Test Redis connection
  command: redis-cli ping
  register: redis_test
  changed_when: false

- name: Display Redis test result
  debug:
    msg: "Redis response: {{ redis_test.stdout }}"
