---
- name: Deploy advertising campaign infrastructure
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vault/secrets.yml

  roles:
      - common

- name: Setup PostgreSQL Master
  hosts: db_master
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - postgres_master

- name: Setup PostgreSQL Slave
  hosts: db_slaves
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - postgres_slave

- name: Setup Redis
  hosts: redis
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - redis

- name: Setup Nginx and PHP-FPM
  hosts: nginx
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - nginx_php

- name: Deploy Application
  hosts: web_servers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - app_deploy

- name: Setup MaxMind GeoIP
  hosts: web_servers
  become: true
  vars_files:
    - vault/secrets.yml
  roles:
      - maxmind
